trex/egg/celebda/urls.py
from django.contrib import admin
from django.urls import path
from celebda import views

app_name = 'celebda'
urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.signup, name='signup'),
    path('login/', views.signin, name='signin'),
    path('<int:account_id>/', views.welcome_index, name='welcome_index'),
    path('<int:account_id>/myprofile/', views.my_profile, name='my_profile'),
    path('<int:account_id>/myprofile/<int:tango_id_self>/', views.subprofile_detail, name='subprofile_detail'),
    path('<int:account_id>/profilecreate/', views.profile_create, name='profile_create'),
    path('<int:account_id>/conditionform/', views.condition_form, name='condition_form'),
    path('<int:account_id>/wishmatchcondition/', views.wish_matchcondition, name='wish_matchcondition'),
    path('<int:account_id>/wishmatchcondition/<int:matchcondition_id>/', views.matchcondition_detail, name='matchcondition_detail'),
    path('<int:account_id>/<int:tango_id>/', views.partner_detail, name='partner_detail'),
    path('<int:account_id>/peekdirect/<int:direct_id>/', views.peek_direct, name='peek_direct'),
    path('<int:account_id>/peekfreak/<int:tango_id>/', views.peek_freak, name='peek_freak'),
    path('<int:account_id>/toggle/<int:tango_id>/', views.profile_like_toggle, name='toggle'),
    path('<int:account_id>/<int:matchcondition_id>/fork/', views.fork, name='fork'),
    path('<int:account_id>/<int:matchcondition_id>/promoterform/', views.promoter_form, name='form_p'),
    path('<int:account_id>/<int:matchcondition_id>/influencerform/', views.influencer_form, name='form_i'),
    path('<int:account_id>/<int:matchcondition_id>/resultspromoter/', views.promoter_results, name='results_p'),
    path('<int:account_id>/<int:matchcondition_id>/resultsinfluencer/', views.influencer_results, name='results_i'),
]
#정규표현식 중 \d가 정수 한자리를 의미하는가?

trex/egg/chat/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<room_name>[^/]+)/$', views.room, name='room'),
]

trex/egg/pilotpage2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('celebda/', include('celebda.urls')),
    path('chat/', include('chat.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trex/egg/celebda/models.py
from django.db import models
from django.contrib.auth.models import User
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.
class MatchCondition(models.Model):
    SEX_CHOICES = (
        ('ML', 'Male'),
        ('FM', 'Female'),
        ('IR', 'Irelevance'),
    )
    sex = models.CharField(max_length=2, choices=SEX_CHOICES)
    AGE_CHOICES = (
        ('10S', '10s'),
        ('20S', '20s'),
        ('30S', '30s'),
        ('40S', '40s'),
        ('50S', '50s'),
        ('60S', '60s'),
        ('IR', 'Irelevance'),
    )
    age = models.CharField(max_length=3, choices=AGE_CHOICES)
    COST_CHOICES = (
        ('1MD', '1m'),
        ('10M', '10m'),
        ('1BU', '1b'),
        ('IR', 'Irelevance'),
    )   
    cost = models.CharField(max_length=3, choices=COST_CHOICES)
    FIELD_CHOICES = (
        ('F&B', 'Foods and Bevarage'),
        ('L&S', 'Leisure and Sports'),
        ('B&C', 'Beauty and Cosmetics'),
        ('IR', 'Irelevance'),
    )
    field = models.CharField(max_length=3, choices=FIELD_CHOICES)

def account_image_path(instance, filename):
    return f'account/{instance.is_promoter}/{instance.user_nick}/{instance.phone_num}.jpg'

def account_thum_path(instance, filename):
    return f'account/{instance.is_promoter}/{instance.user_nick}/{instance.phone_num}_thum.jpg'

class Account(models.Model):
    user_nick = models.CharField(max_length=30)
    introduce = models.TextField()
    phone_num = models.CharField(max_length=11)
    photo = ProcessedImageField(
                upload_to = account_image_path,
                processors = [ResizeToFill(300,350)], 
                format = 'JPEG', 
                options = {'quality': 90 }, 
        )
    thum = ProcessedImageField(
                upload_to = account_thum_path,
                processors = [ResizeToFill(90,90)],
                format = 'JPEG',
                options = {'quality': 90 },
        )
    PARTNER_CHOICES = (
        ('P', 'Promoter'),
        ('I', 'Influencer'),
    )
    is_promoter = models.CharField(max_length=1, choices=PARTNER_CHOICES)
    join_date = models.DateTimeField(auto_now_add=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user_nick

class Promoter(models.Model):
    id_name = models.CharField(max_length=30)
    introduce = models.CharField(max_length=200)
    join_date = models.DateTimeField(auto_now_add=True)
    matchcon = models.ForeignKey(MatchCondition, on_delete=models.CASCADE)
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    like = models.ManyToManyField(Account, blank=True, related_name='like_promoter')
    like_count = models.PositiveIntegerField(default=0)
    
    def __str__(self):
        return self.id_name

class Influencer(models.Model):
    id_name = models.CharField(max_length=30)
    introduce = models.CharField(max_length=200)
    join_date = models.DateTimeField(auto_now_add=True)
    matchcon = models.ForeignKey(MatchCondition, on_delete=models.CASCADE)
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    like = models.ManyToManyField(Account, blank=True, related_name='like_influencer')
    like_count = models.PositiveIntegerField(default=0)
    
    def __str__(self):
        return self.id_name

#https://infinitt.tistory.com/65?category=1072777

#https://dheldh77.tistory.com/entry/Django-%EC%9D%B4%EB%AF%B8%EC%A7%80-%EC%97%85%EB%A1%9C%EB%93%9C
#https://wayhome25.github.io/django/2017/05/10/media-file/ 
#https://tothefullest08.github.io/django/2019/06/04/Django17_image/

trex/egg/celebda/forms.py
from django.forms import ModelForm
from django import forms
from celebda.models import MatchCondition, Promoter, Influencer, Account
from django.contrib.auth.models import User

class MatchConditionForm(forms.ModelForm):
    class Meta:
        model = MatchCondition
        fields = ['sex', 'age', 'cost', 'field']

class PromoterForm(forms.ModelForm):
    class Meta:
        model = Promoter
        fields = ['id_name', 'introduce']
        
class InfluencerForm(forms.ModelForm):
    class Meta:
        model = Influencer
        fields = ['id_name', 'introduce']
        
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password', 'email']
        
class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']

class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['user_nick', 'introduce', 'phone_num', 'is_promoter']

trex/egg/celebda/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views.generic import View
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
from django.contrib import auth
from celebda.models import MatchCondition, Promoter, Influencer, Account
from celebda.forms import MatchConditionForm, PromoterForm, InfluencerForm, UserForm, AccountForm, LoginForm
from django.db.models import Q
#데코레이터 @login required -> 보안에 필요.

# Create your views here.
#인덱스폼->매치컨디션DB채움->유저폼->I or P 결정(간단한)->각각에 맞는 결과 저장후 ->해당매치컨디션에 딸려있는 프로모터와 인플루언서를 교차하여 제출.
#index -> signin or signup -> welcome_index or profile_create -> welcome_index

def index(request):
    return render(request, 'celebda/index.html')

def welcome_index(request, account_id):#내가 Like한 유저, 새로가입한 유저를 갖고옴
    account_now = get_object_or_404(Account, pk=account_id)
    context = user_bringer(account_id)
    context['account_now'] = account_now
    return render(request, 'celebda/welcome_index.html', context)
    
def my_profile(request, account_id):
    account_now = get_object_or_404(Account, pk=account_id)
    context = subprofile_bringer(account_id)
    context_a = {'account_now': account_now}
    context.update(context_a)
    return render(request, 'celebda/my_profile.html', context)
    
def profile_create(request, account_id):#나중에 code cleaning (account_id=>register_id)할것!!!!!! 존나 헷갈림..
    if request.method == "POST":
        i_user_nick = request.POST['new_user_nick'] 
        i_introduce = request.POST['new_introduce']
        i_phone_num = request.POST['new_phone_num']
        i_is_promter = request.POST['iorp']
        i_photo = request.FILES.get('photo')
        new_account = Account(
            id=account_id,#Account와 User간의 pk-Syncro가 되어있지 않으면 welcome_index에서 404를 반환(Account는 3까지 생성됐는데 User pk=8, Account pk=8인 경우)
            user_id=account_id,
            user_nick=i_user_nick,
            phone_num=i_phone_num,
            introduce=i_introduce,
            is_promoter=i_is_promter,
            photo=i_photo,
            thum=i_photo,
        )
        new_account.save()
        return HttpResponseRedirect(reverse('celebda:welcome_index', args=(new_account.id,)))            
    else:
        return render(request, 'celebda/profile_create.html', {
            'account_id': account_id,
        })
    
def wish_matchcondition(request, account_id):#QRM 순서 어카운트->프/인->[매치콘]->인/프.
    pk_list=[]
    account_now = get_object_or_404(Account, pk=account_id)
    context = user_bringer(account_id)
    context_m = match_bringer(account_id)
    context.update(context_m)
    context['account_now'] = account_now
    return render(request, 'celebda/wish_match.html', context)
    
def matchcondition_detail(request, account_id, matchcondition_id):
    account_now = get_object_or_404(Account, pk=account_id)
    if account_now.is_promoter == 'P':
        context = promoter_results_maker(request, account_id, matchcondition_id)
    else:
        context = influencer_results_maker(request, account_id, matchcondition_id)
    return render(request, 'celebda/match_detail.html', context)

def subprofile_detail(request, account_id, tango_id_self):
    tango_id = tango_id_self
    account_now = get_object_or_404(Account, pk=account_id)
    if account_now.is_promoter == 'P':
        tango = get_object_or_404(Promoter, pk=tango_id)
    else:
        tango = get_object_or_404(Influencer, pk=tango_id)
    context = {
        'tango': tango,
        'account_now': account_now,
    }
    return render(request, 'celebda/partner_detail.html', context)

def partner_detail(request, account_id, tango_id):
    account_now = get_object_or_404(Account, pk=account_id)
    if account_now.is_promoter == 'P':
        tango = get_object_or_404(Influencer, pk=tango_id)
    else:
        tango = get_object_or_404(Promoter, pk=tango_id)
    context = {
        'tango': tango,
        'account_now': account_now,
    }
    return render(request, 'celebda/partner_detail.html', context)

"""def influencer_detail(request, account_id, influencer_id):
    account_now = get_object_or_404(Account, pk=account_id)
    tango = get_object_or_404(Influencer, pk=influencer_id)
    context = {
        'tango': tango,
        'account_now': account_now,
    }
    return render(request, 'celebda/influencer_detail.html', context)"""
    
def profile_like_toggle(request, account_id, tango_id):
    account_now = get_object_or_404(Account, pk=account_id)
    if account_now.is_promoter == 'P':
        influencer = get_object_or_404(Influencer, pk=tango_id)
        check_like_influencer = influencer.like.filter(id=account_id)
        if check_like_influencer.exists():
            influencer.like.remove(account_now)
            influencer.like_count -= 1
            influencer.save()
        else:
            influencer.like.add(account_now)
            influencer.like_count += 1
            influencer.save()
        return HttpResponseRedirect(reverse('celebda:partner_detail', kwargs={'account_id':account_now.id, 'tango_id':influencer.id}))
    else:
        promoter = get_object_or_404(Promoter, pk=tango_id)
        check_like_promoter = promoter.like.filter(id=account_id)
        if check_like_promoter.exists():
            promoter.like.remove(account_now)
            promoter.like_count -= 1
            promoter.save()
        else:
            promoter.like.add(account_now)
            promoter.like_count += 1
            promoter.save()        
        return HttpResponseRedirect(reverse('celebda:partner_detail', kwargs={'account_id':account_now.id, 'tango_id':promoter.id}))

"""def profile_like_toggle_i(request, account_id, influencer_id):
    influencer = get_object_or_404(Influencer, pk=influencer_id)
    account_now = get_object_or_404(Account, pk=account_id)
    check_like_influencer = influencer.like.filter(id=account_id)
    if check_like_influencer.exists():
        influencer.like.remove(account_now)
        influencer.like_count -= 1
        influencer.save()
    else:
        influencer.like.add(account_now)
        influencer.like_count += 1
        influencer.save()
    return HttpResponseRedirect(reverse('celebda:detail_i', args=(account_now.id, influencer.id,)))"""
    
def peek_freak(request, account_id, tango_id):#contract_detail.html 또는 다른 html에서 peek_num(상대 Influencer or Promoter의 id)을 받아온다.
    account_now = get_object_or_404(Account, pk=account_id)
    if account_now.is_promoter == 'P':
        tango = get_object_or_404(Influencer, pk=tango_id)
    else:
        tango = get_object_or_404(Promoter, pk=tango_id)
    peek_key = tango.account_id
    peeked_account = get_object_or_404(Account, pk=peek_key)
    context_a = subprofile_bringer(account_id=peek_key)
    context = {
        'peeked_account': peeked_account,
        'account_now': account_now,
    }
    context.update(context_a)
    return render(request, 'celebda/peek_freak.html', context)
    
def peek_direct(request, account_id, direct_id):
    account_now = get_object_or_404(Account, pk=account_id)
    peeked_account = get_object_or_404(Account, pk=direct_id)
    context_a = subprofile_bringer(account_id=direct_id)
    context = {
        'peeked_account': peeked_account,
        'account_now': account_now,
    }
    context.update(context_a)
    return render(request, 'celebda/peek_freak.html', context)

def condition_form(request, account_id):
    account_now = get_object_or_404(Account, pk=account_id)
    template_name = 'celebda/condition_form.html'
    if request.method == "POST":
        i_sex = request.POST['sex']
        i_age = request.POST['age']
        i_cost = request.POST['cost']
        i_field = request.POST['field']
        try:
            #Chaning, LAZY.         
            queryset = MatchCondition.objects.all()
            queryset = queryset.filter(sex=i_sex)
            queryset = queryset.filter(age=i_age)
            queryset = queryset.filter(cost=i_cost)
            queryset = queryset.get(field=i_field)
            matchcondition_id = queryset.id
            return HttpResponseRedirect(reverse('celebda:fork', kwargs={'account_id':account_now.id, 'matchcondition_id':matchcondition_id}))
                #pk로 넘겨주는것->이미 존재하는 매치콘디션의 id. 지연연산을 통해 리턴된 쿼리셋이 중복일 경우를 요주의할 것. 
        except:           
            new_condition = MatchCondition(sex=i_sex, age=i_age, cost=i_cost, field=i_field)
            new_condition.save()
            matchcondition_id = new_condition.id 
            return HttpResponseRedirect(reverse('celebda:fork', kwargs={'account_id':account_now.id, 'matchcondition_id':matchcondition_id}))#'%s/%s/fork/' %(account_num, pk)?
    else:
        return render(request, template_name, {
            'account_now': account_now,
        })

def fork(request, account_id, matchcondition_id): #공사중
    account_now = get_object_or_404(Account, pk=account_id)
    matchcondition = get_object_or_404(MatchCondition, pk=matchcondition_id)
    if account_now.is_promoter == 'P':
        return HttpResponseRedirect(reverse('celebda:form_p', kwargs={'account_id':account_now.id, 'matchcondition_id':matchcondition.id}))
    else:
        return HttpResponseRedirect(reverse('celebda:form_i', kwargs={'account_id':account_now.id, 'matchcondition_id':matchcondition.id}))
#위 HttpResponseRedirect에서 쓴 방법과 다르며, 무어가 맞는지 판단할 필요가 있습니다.

def promoter_form(request, account_id, matchcondition_id):
    account_now = get_object_or_404(Account, pk=account_id)
    matchcondition = get_object_or_404(MatchCondition, pk=matchcondition_id)
        
    if request.method == "POST":
        i_id_name = request.POST['new_id_name']
        i_introduce = request.POST['new_introduce']
        new_promoter = Promoter(account_id=account_now.id, matchcon_id=matchcondition.id, id_name=i_id_name, introduce=i_introduce)
        new_promoter.save()#외래키를 지정할 때는 그냥 'match'아닌 'match_id'로 정해주어야 함.

trex/egg/celebda/templates/celebda/welcome_index.html
<!DOCTYPE html>
<!-- this site is created with : http://www.iueditor.org -->
<HTML>
	<head>
		{% load static %}
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" type="text/css" href="{% static '/resources/css/iu.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static '/resources/css/compositions/header.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static '/resources/css/compositions/footer.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static '/resources/css/pages/index.css' %}">
		<link rel="stylesheet" type="text/css" href="https://cdn.rawgit.com/openhiun/hangul/14c0f6faa2941116bb53001d6a7dcd5e82300c3f/nanumbarungothic.css">
		<link rel="stylesheet" type="text/css" href="https://cdn.rawgit.com/openhiun/hangul/14c0f6faa2941116bb53001d6a7dcd5e82300c3f/nanumbarungothic.css">
		<link rel="stylesheet" type="text/css" href="https://cdn.rawgit.com/openhiun/hangul/14c0f6faa2941116bb53001d6a7dcd5e82300c3f/nanumbarungothic.css">
		<link rel="stylesheet" type="text/css" href="https://cdn.rawgit.com/openhiun/hangul/14c0f6faa2941116bb53001d6a7dcd5e82300c3f/nanumbarungothic.css">
		<link rel="stylesheet" type="text/css" href="https://cdn.rawgit.com/openhiun/hangul/14c0f6faa2941116bb53001d6a7dcd5e82300c3f/nanumbarungothic.css">
		<link rel="stylesheet" type="text/css" href="https://cdn.rawgit.com/openhiun/hangul/14c0f6faa2941116bb53001d6a7dcd5e82300c3f/nanumbarungothic.css">
		<script type="text/javascript" src="//cdn.iueditor.org/js/iueditor-2.1.js"></script>
		<script type="text/javascript" src="{% static '/resources/js/iuevent.js' %}"></script>
		<!--[if lt IE 9]>
			<script>
				document.createElement("header")
				document.createElement("footer")
				document.createElement("section")
				document.createElement("nav")
				document.createElement("article")
			</script>
			<noscript>
				<strong>Warning !</strong>
				Because your browser does not support HTML5, some elements are simulated using JScript.
				Unfortunately your browser has disabled scripting. Please enable it in order to display this page.
			</noscript>
		<![endif]-->
	</head>
	<body>
	<div class="iu-page iu-page-1">
		<div class="iu-header iu-header-2 iu-composition-12">
			<a href="{% url 'celebda:welcome_index' account_id=account_now.id %}"><div class="iu-floating-image iu-floating-image-12"></div></a>
			<div class="iu-floating-image iu-floating-image-13"></div>
			<a href="{% url 'celebda:index' %}"><div class="iu-floating-image iu-floating-image-14"></div>
			<div class="iu-floating-image iu-floating-image-15"></div>
			<a href="{% url 'celebda:wish_matchcondition' account_id=account_now.id %}"><div class="iu-floating-image iu-floating-image-16"></div></a>
			<div class="iu-icon-button iu-icon-button-20">
				<p>
					<span>
					<a href="{% url 'celebda:my_profile' account_id=account_now.id %}">{{account_now.user_nick}}</a>
					</span>
					<img src="{% static '/resources/images/user_icn0.jpg' %}"/>
				</p>
			</div>
		</div>
		<div class="iu-page-content iu-page-content-3">
			<section class="iu-section iu-section-4">
				<div class="iu-box iu-box-29">
					<div class="iu-box iu-box-34">
						<div class="iu-icon-button iu-icon-button-38">
							<p>
								{% if freshman_1.thum %}
									<img src="{{ freshman_1.thum.url }}"/>
								{% endif %}
								<span>
								<a href="{% url 'celebda:peek_direct' account_id=account_now.id direct_id=freshman_1.id %}">{{freshman_1.user_nick}}</a>
								</span>
							</p>
						</div>
						<div class="iu-icon-button iu-icon-button-39">
							<p>
								{% if freshman_2.thum %}
									<img src="{{ freshman_2.thum.url }}"/>
								{% endif %}
								<span>
								<a href="{% url 'celebda:peek_direct' account_id=account_now.id direct_id=freshman_2.id %}">{{freshman_2.user_nick}}</a>
								</span>
							</p>
						</div>
						<div class="iu-icon-button iu-icon-button-40">
							<p>
								{% if freshman_3.thum %}
									<img src="{{ freshman_3.thum.url }}"/>
								{% endif %}
								<span>
								<a href="{% url 'celebda:peek_direct' account_id=account_now.id direct_id=freshman_3.id %}">{{freshman_3.user_nick}}</a>
								</span>
							</p>
						</div>
					</div>
					<div class="iu-box iu-box-35">
						<div class="iu-icon-button iu-icon-button-41">
							<p>
								{% if likedone_1.account.thum %}
									<img src="{{ likedone_1.account.thum.url }}"/>
								{% endif %}
								<span>
								{% if likedone_1 != None %}
									<a href="{% url 'celebda:partner_detail' account_id=account_now.id tango_id=likedone_1.id %}">{{likedone_1.id_name}}</a>
								{% else %}
								{% endif %}
								</span>
							</p>
						</div>
						<div class="iu-icon-button iu-icon-button-42">
							<p>
								{% if likedone_2.account.thum %}
									<img src="{{ likedone_2.account.thum.url }}"/>
								{% endif %}
								<span>
								{% if likedone_2 != None %}
									<a href="{% url 'celebda:partner_detail' account_id=account_now.id tango_id=likedone_2.id %}">{{likedone_2.id_name}}</a>
								{% else %}
								{% endif %}
								</span>
							</p>
						</div>
						<div class="iu-icon-button iu-icon-button-43">
							<p>
								{% if likedone_3.account.thum %}
									<img src="{{ likedone_3.account.thum.url }}"/>
								{% endif %}
								<span>
								{% if likedone_3 != None %}
									<a href="{% url 'celebda:partner_detail' account_id=account_now.id tango_id=likedone_3.id %}">{{likedone_3.id_name}}</a>
								{% else %}
								{% endif %}
								</span>
							</p>
						</div>
						<div class="iu-icon-button iu-icon-button-44">
							<p>
								{% if likedone_4.account.thum %}
									<img src="{{ likedone_4.account.thum.url }}"/>
								{% endif %}
								<span>
								{% if likedone_4 != None %}
									<a href="{% url 'celebda:partner_detail' account_id=account_now.id tango_id=likedone_4.id %}">{{likedone_4.id_name}}</a>
								{% else %}
								{% endif %}
								</span>
							</p>
						</div>
					</div>
					<div class="iu-text iu-text-36">
						<p>New Arrivals!;</p>
						<p>새로운 비즈니스 파트너를 만나보세요.</p>
					</div>
					<div class="iu-text iu-text-37">
						<p>내 관심 파트너;</p>
						<p>놓치지 않게 주의!</p>
					</div>
					<div class="iu-text iu-text-44">
						<a href="{% url 'celebda:wish_matchcondition' account_id=account_now.id %}"><p>[더보기]</p></a>
					</div>
				</div>
				<div class="iu-box iu-box-42">
					<div class="iu-box iu-box-51">
						<div class="iu-text iu-text-46">
							<p>Find Out!;</p>
							<p>희망사항을 입력 해주시면, 즉시 비즈니스 파트너와 연결합니다.</p>
						</div>
						<div class="iu-cell iu-cell-57">
							<p>#뷰티</p>
						</div>
						<div class="iu-cell iu-cell-55">
							<p>#키즈</p>
						</div>
						<div class="iu-cell iu-cell-54">
							<p>#셀럽</p>
						</div>
						<div class="iu-cell iu-cell-58">
							<p>#먹방</p>
						</div>
						<div class="iu-cell iu-cell-56">
							<p>#스포츠</p>
						</div>
						<div class="iu-text iu-text-52">
							<p>Find Out!;</p>
							<p>희망사항을 입력 해주시면, 즉시 비즈니스 파트너와 연결합니다.</p>
						</div>
						<div class="iu-cell iu-cell-89">
							<a href="{% url 'celebda:condition_form' account_id=account_now.id %}"><p>아주 빠르게!</p></a>
						</div>
					</div>
				</div>
				<div class="iu-box iu-box-44">
					<div class="iu-text iu-text-45">
						<p><em>CelebDA</em>는;</p>
						<p>창의적인 인플루언서들의 안정적&nbsp;발전을 지원하고,</p>
						<p>기업 광고 홍보담당자들에 프로모션에 대한 인사이트를 제공합니다.</p>
					</div>
					<div class="iu-carousel iu-carousel-84" data-iu-carousel-time="4000">
						<div class="iux-carousel-wrapper">
							<div class="iu-carousel-item iu-carousel-item-85"></div>
							<div class="iu-carousel-item iu-carousel-item-86"></div>
							<div class="iu-carousel-item iu-carousel-item-87"></div>
						</div>
						<div class="iux-carousel-next"></div>
						<div class="iux-carousel-prev"></div>
						<ul class="iux-carousel-pager">
							<li></li>
							<li></li>
							<li></li>
						</ul>
					</div>
				</div>
			</section>
		</div>
		<div class="iu-footer iu-footer-7 iu-composition-11">
			<div class="iu-floating-image iu-floating-image-17"></div>
			<div class="iu-text iu-text-23">
				<p>Company:20Trendy.Inc., Owner:송민준</p>
				<p>통신사업자:2021서울동대문523호</p>
				<p>개인정보관리자:최준혁,znhyk@gmail.com</p>
				<p>주소:서울특별시 동대문구 이문로 64-11</p>
				<p>20Trendy@ALL Rights reserved. designed by znhyk.</p>
			</div>
		</div>
	</div>
	<div id="iux-popup-dimcolor" class="iux-popup-dimcolor"></div>
	<div id="iux-panel-dimcolor" class="iux-panel-dimcolor"></div>
	</body>
</HTML>