trex/egg/celebda/urls.py
from django.contrib import admin
from django.urls import path
from celebda import views

app_name = 'celebda'
urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.signup, name='signup'),
    path('login/', views.signin, name='signin'),
    path('<int:account_id>/', views.welcome_index, name='welcome_index'),
    path('<int:account_id>/myprofile/', views.my_profile, name='my_profile'),
    path('<int:account_id>/myprofile/<int:tango_id_self>/', views.subprofile_detail, name='subprofile_detail'),
    path('<int:account_id>/profilecreate/', views.profile_create, name='profile_create'),
    path('<int:account_id>/conditionform/', views.condition_form, name='condition_form'),
    path('<int:account_id>/wishmatchcondition/', views.wish_matchcondition, name='wish_matchcondition'),
    path('<int:account_id>/wishmatchcondition/<int:matchcondition_id>/', views.matchcondition_detail, name='matchcondition_detail'),
    path('<int:account_id>/<int:tango_id>/', views.partner_detail, name='partner_detail'),
    path('<int:account_id>/peekdirect/<int:direct_id>/', views.peek_direct, name='peek_direct'),
    path('<int:account_id>/peekfreak/<int:tango_id>/', views.peek_freak, name='peek_freak'),
    path('<int:account_id>/toggle/<int:tango_id>/', views.profile_like_toggle, name='toggle'),
    path('<int:account_id>/<int:matchcondition_id>/fork/', views.fork, name='fork'),
    path('<int:account_id>/<int:matchcondition_id>/promoterform/', views.promoter_form, name='form_p'),
    path('<int:account_id>/<int:matchcondition_id>/influencerform/', views.influencer_form, name='form_i'),
    path('<int:account_id>/<int:matchcondition_id>/resultspromoter/', views.promoter_results, name='results_p'),
    path('<int:account_id>/<int:matchcondition_id>/resultsinfluencer/', views.influencer_results, name='results_i'),
]
#정규표현식 중 \d가 정수 한자리를 의미하는가?

trex/egg/chat/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<room_name>[^/]+)/$', views.room, name='room'),
]

trex/egg/pilotpage2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('celebda/', include('celebda.urls')),
    path('chat/', include('chat.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trex/egg/templates/base_celebda.html
<!DOCTYPE html>
<!-- this site is created with : http://www.iueditor.org -->
<HTML>
	<head>
	    {% load static %}
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" type="text/css" href="{% static '/resources/css/iu.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static '/resources/css/compositions/header.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static '/resources/css/compositions/footer.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static '/resources/css/pages/page1.css' %}">
		<script type="text/javascript" src="//cdn.iueditor.org/js/iueditor-2.1.js"></script>
		<script type="text/javascript" src="{% static '/resources/js/iuevent.js' %}"></script>
		<!--[if lt IE 9]>
			<script>
				document.createElement("header")
				document.createElement("footer")
				document.createElement("section")
				document.createElement("nav")
				document.createElement("article")
			</script>
			<noscript>
				<strong>Warning !</strong>
				Because your browser does not support HTML5, some elements are simulated using JScript.
				Unfortunately your browser has disabled scripting. Please enable it in order to display this page.
			</noscript>
		<![endif]-->
	</head>
	<body>
	<div class="iu-page iu-page-74">
		<div class="iu-header iu-header-75 iu-composition-12">
			<a href="{% url 'celebda:welcome_index' account_id=account_now.id %}"><div class="iu-floating-image iu-floating-image-12"></div></a>
			<div class="iu-floating-image iu-floating-image-13"></div>
			<div class="iu-floating-image iu-floating-image-14"></div>
			<div class="iu-floating-image iu-floating-image-15"></div>
			<div class="iu-floating-image iu-floating-image-16"></div>
			<div class="iu-icon-button iu-icon-button-20">
				<p>
					<span>
					{% block usercontent %}{% endblock %}
					</span>
					<img src="{% static '/resources/images/user_icn0.jpg' %}"/>
				</p>
			</div>
		</div>
		<div id="content">
	        {% block content %}{% endblock %}
	    </div>
		<div class="iu-footer iu-footer-80 iu-composition-11">
			<div class="iu-floating-image iu-floating-image-17"></div>
			<div class="iu-text iu-text-23">
				<p>Company:20Trendy.Inc., Owner:송민준</p>
				<p>통신사업자:2021서울동대문523호</p>
				<p>개인정보관리자:최준혁,znhyk@gmail.com</p>
				<p>주소:서울특별시 동대문구 이문로 64-11</p>
				<p>20Trendy@ALL Rights reserved. designed by znhyk.</p>
			</div>
		</div>
	</div>
	<div id="iux-popup-dimcolor" class="iux-popup-dimcolor"></div>
	<div id="iux-panel-dimcolor" class="iux-panel-dimcolor"></div>
	</body>
</HTML>